# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
workspace 'iOS Example.xcworkspace'



target 'iOS Example' do
  use_frameworks!
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift'
end
